# /Users/eliram/.config/tmuxinator/concord.yml
---

name: Concord
root: ~/code/anaplan/concord
pre_window: source concord.env
windows:
  - runners:
      layout: tiled
      panes:
        - manager:
          - rabbitmq-server &
          - printf '\033]2;%s\033\\' 'Job Manager' 
          - cd concord-job-manager 
          - python3 -m concordjm.concord_job_manager
        - managerApis:
          - printf '\033]2;%s\033\\' 'Job Manager API'
          - cd concord-job-manager
          - python3 -m concordjm.concord_job_manager_api
        - IOWorker:
          - printf '\033]2;%s\033\\' 'IOWorker'
          - cd concord-io-workers
          - python3 -m concordio.ioworker
        - API:
          - printf '\033]2;%s\033\\' 'API'
          - cd concord-api
          - python3 -m concordapi.concord_api
  - job-manager:
      root: ~/code/anaplan/concord/concord-job-manager
      layout: main-vertical
      panes:
        - nvim:
          - printf '\033]2;%s\033\\' 'Job Manager' 
          - nvim
        # - lazygit:
        # - lazygit
  - io-worker:
      root: ~/code/anaplan/concord/concord-io-workers
      layout: main-vertical
      panes:
        - nvim:
          - printf '\033]2;%s\033\\' 'IOWorker' 
          - nvim
        # - lazygit:
        # - lazygit
  - api:
      root: ~/code/anaplan/concord/concord-api
      layout: main-vertical
      panes:
        - nvim:
          - printf '\033]2;%s\033\\' 'API' 
          - nvim
        # - lazygit:
        # - lazygit
