format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:directory_color_bg fg:#a3aed2)\
$directory\
$git_branch\
$git_status\
$kubernetes\
$nodejs\
$python\
$java\
$gradle\
[](fg:#1d2230)\
\n$time\
$battery\
$character"""

command_timeout = 10000


# Set 'foo' as custom color palette
palette = 'eliram'

# Define custom colors
[palettes.eliram]
directory_color_fg = '#e3e5e5'
directory_color_bg = '#769ff0'
git_color_fg = '#769ff0'
git_color_bg = '#394260'

langs_coloer_fg = '#769ff0'
langs_coloer_bg = '#212736'

# Overwrite existing color
blue = '21'
# Define new color
mustard = '#af8700'


[battery]
full_symbol = "🔋 "
charging_symbol = "⚡️ "
discharging_symbol = "💀 "

[[battery.display]]
threshold = 40
style = "bold red"

[kubernetes]
format = 'on [⛵ $context \($namespace\)](dimmed green) '
disabled = false
[kubernetes.context_aliases]
"arn:aws:eks:us-east-1:189840129916:cluster/np-eks" = "non-prod"

[directory]
style = "fg:directory_color_fg bg:directory_color_bg"
format = "[ $path ]($style)[](fg:directory_color_bg bg:git_color_bg)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "fg:git_color_fg bg:git_color_bg"
format = '[[ $symbol $branch ]($style)]($style)'

[git_status]
style = "fg:git_color_fg bg:git_color_bg"
format = '[[($all_status$ahead_behind )]($style)]($style)[](fg:git_color_bg bg:#212736)'

[nodejs]
symbol = ""
style = "fg:langs_coloer_fg bg:langs_coloer_bg"
format = '[[ $symbol ($version) ]($style)]($style)[](fg:#212736 bg:#212736)'

[python]
style = "fg:langs_coloer_fg bg:langs_coloer_bg"
format = '[[ $symbol ($version) ( pyenv:$virtualenv) ]($style)]($style)[](fg:#212736 bg:#212736)'

[java]
style = "fg:langs_coloer_fg bg:langs_coloer_bg"
format = '[[ $symbol ($version) ]($style)]($style)[](fg:#212736 bg:#212736)'

[gradle]
style = "fg:langs_coloer_fg bg:langs_coloer_bg"
format = '[[ $symbol ($version) ]($style)]($style)[](fg:#212736 bg:#212736)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)[](fg:#1d2230)'

[direnv]
disabled = false
